const LunchData = [
    {
      id: "1",
      category: "Assorted Sushi & Noodles ( 모듬 스시 & 누들)",
      title: "Maru A (마루 A)",
      price: "14.95",
      img: "",
      desc: "5 Nigiri: 1 Salmon, 1 Tuna, 1 Shrimp, 1 Snapper, 1 Butter fish",
      desc1:'2 Sashimi: 2 Salmon',
    },
    {
        id: "2",
        category: "Assorted Sushi & Noodles ( 모듬 스시 & 누들)",
        title: " Maru B (마루 B)",
        price: "16.95",
        img: require("../../assets/images/Lunch/maru-b.jpg"),
        desc: "5 Nigiri: 1 Salmon, 1 Tuna, 1 Shrimp, 1 Butter fish, 1 Unagi   ",
        desc1:'3 California, 3 Spicy Salmon',
      },
      {
        id: "3",
        category: "Assorted Sushi & Noodles ( 모듬 스시 & 누들)",
        title: "Maru C (마루 C)",
        price: "18.95",
        img: require("../../assets/images/Lunch/maru-c.jpg"),
        desc: " 6 Sashimi: 2 Salmon, 2 Tuna, 2 Snapper ",
        desc1:'3 Nigiri Sushi: 1 Salmon, 1 Tuna, 1 Shrimp ',
        desc2: "3 California Roll, 3 Spicy Salmon Roll",
      },
      {
        id: "4",
        category: "Assorted Sushi & Noodles ( 모듬 스시 & 누들)",
        title: "Maru D (마루 D)",
        price: "16.95",
        img: require("../../assets/images/Lunch/maru-d.jpg"),
        desc: "10 Sashimi: 2 Salmon, 2 Tuna, 2 Unagi, 2 Butter fish, 2 Surf Clam  ",
      },
      {
        id: "5",
        category: "Assorted Sushi & Noodles ( 모듬 스시 & 누들)",
        title: "Maru E (마루 E)",
        price: "13.95",
        img: "",
        desc: " 10 Sashimi: 2 Salmon, 2 Tuna, 2 Unagi, 2 Butter fish, 2 Surf Clam ",
      },
      {
        id: "6",
        category: "Lunch Bento(도시락)",
        title: "Teriyaki Chicken",
        price: "13.95",
        img: "",
        desc: "choose one: Spring Roll, Sushi Roll, Dumplings, Assorted Tempura",
        desc1:'Served with Rice, Salad and Miso soup',
      },
      {
        id: "7",
        category: "Lunch Bento(도시락)",
        title: "Teriyaki Beef ",
        price: "13.95",
        img: require("../../assets/images/Lunch/teriyaki-beef.jpg"),
         desc: "choose one: Spring Roll, Sushi Roll, Dumplings, Assorted Tempura",
        desc1:'Served with Rice, Salad and Miso soup',
      },
      {
        id: "8",
        category: "Lunch Bento(도시락)",
        title: "Tonkatsu(Pork Cutlet)",
        price: "13.95",
        img: "",
         desc: "choose one: Spring Roll, Sushi Roll, Dumplings, Assorted Tempura",
        desc1:'Served with Rice, Salad and Miso soup',
      },
]

export default LunchData;
